inputs:
  ruby-version:
    description: Ruby version
    required: false
    default: '3.3'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
    - run: ruby "$GITHUB_ACTION_PATH"/../../../bin/git-submodule-fast-install
      shell: bash
    - run: yarn install
      shell: bash
      working-directory: ${{ github.action_path }}/../../..
