name: build

on:
  push:
    branches:
      - master
      - '*-stable'
      - '*/ci-check'
  pull_request: {}

permissions:
  contents: read

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        # Currently failing:
        # ruby: truffleruby, jruby
        ruby: ['3.0', '3.1', '3.2', '3.3']
        os: [ubuntu-latest]
        include:
          - ruby: 3.3
            os: windows-latest
          - ruby: 3.3
            os: macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ruby == 'head' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle exec rake rspec

  minitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bin/rake minitest

  minitest-strict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bin/rake minitest
        env:
          USE_STRICT: 'true'

  minitest-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bundle exec rake minitest

  mspec:
    name: mspec-${{ matrix.platform }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        platform: [nodejs, chrome]
        os: [ubuntu-latest, windows-latest]
        include:
          - platform: safari
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bundle exec rake mspec_${{ matrix.platform }}

  mspec-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - id: setup-firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '106.0.4'
      - run: xvfb-run bin/rake mspec_firefox
        env:
          MOZILLA_FIREFOX_BINARY: ${{ steps.setup-firefox.outputs.firefox-path }}

  # mspec-firefox-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup
  #     - id: setup-firefox
  #       uses: browser-actions/setup-firefox@latest
  #       with:
  #         firefox-version: '106.0.4'
  #     - run: bundle exec rake mspec_firefox
  #       env:
  #         MOZILLA_FIREFOX_BINARY: ${{ steps.setup-firefox.outputs.firefox-path }}

  mspec-bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: oven-sh/setup-bun@v1
      - run: bundle exec rake mspec_bun

  timezone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bin/rake mspec_nodejs TZ="Pacific/Fiji"

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bin/rake smoke_test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bin/rake lint

  performance:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: oven-sh/setup-bun@v1
      - run: bin/rake performance:compare
